title:              Assist Casa
email:              avishay.il@gmail.com
description:        "Unlocking the power of home automation: Tips, integrations, and smart devices for a seamless, connected home with Home Assistant"
author:             Avishay Bar
baseurl:            "/"
url:                "https://assist.casa"

# Social Profiles
github_username:    avishayil
linkedin_username:  avishaybar

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-HEWHTYV2YJ # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

# GitHub pages
domain: assistcasa.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://assistcasa.github.io  # the base hostname and protocol for your site, e.g. http://example.com